#!/bin/bash

cut -d, -f1-5 --output-delimiter=$'\n' modaccess.txt > newredirect.txt
# Global variables declarations
usr_ID="SomeID"
a_token="Sometoken"
a_token_s="Somesecret"
c_key="Somekey"
c_key_s="Someksecret"
let counter=1
let num=1                				     # Keeps track of which key is being processed
let offsetStart=0
let offset=400

while read f
do
  if [ $counter -eq 1 ]
     then
        usr_ID=$f
        let counter=counter+1
  elif [ $counter -eq 2 ]
     then
        a_token=$f
        let counter=counter+1
  elif [ $counter -eq 3 ]
     then
        a_token_s=$f
        let counter=counter+1
  elif [ $counter -eq 4 ]
      then
        c_key=$f
        let counter=counter+1
  elif [ $counter -eq 5 ]
      then
        c_key_s=$f
        let counter=1                                                                # Restart the counter back to 1
        let temp=$offsetStart                                                        # Set the temporary start
        if ! test -f "April_TB_"$temp"_"$offset".json"
           then
               touch "April_TB_"$temp"_"$offset".json"
        fi
        ./listener.py $usr_ID $a_token $a_token_s $c_key $c_key_s $temp $offset &     # Run the script as a separate process
        echo "Starting process with offsets $temp and $offset"
        let offsetStart=offset			                                # Change the id offset start for the next process
        let offset=offset+400                                                        # Increment the number of users to process
        echo "The new offsets are $offsetStart $offset"
  fi
done < newredirect.txt      # Extract only the token keys


    
    
